import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

class WorkingPDFService {
  async generateReport(order: any, analysisResult: any): Promise<string> {
    const filename = `color-analysis-${order.id}-${Date.now()}.pdf`;
    const filePath = path.join('uploads', 'reports', filename);
    
    // Ensure directory exists
    const dir = path.dirname(filePath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ 
          size: 'A4',
          margin: 50,
          info: {
            Title: `${analysisResult.season} Color Analysis Report`,
            Author: 'HueMatcher Professional Color Analysis'
          }
        });
        
        const stream = fs.createWriteStream(filePath);
        doc.pipe(stream);

        // Cover Page
        this.generateCoverPage(doc, analysisResult);
        
        // Palette Page
        doc.addPage();
        this.generatePalettePage(doc, analysisResult);
        
        // Recommendations Page
        doc.addPage();
        this.generateRecommendationsPage(doc, analysisResult);

        doc.end();
        
        stream.on('finish', () => {
          console.log('PDF generated successfully at:', filePath);
          resolve(filePath);
        });
        
        stream.on('error', (error) => {
          console.error('PDF generation error:', error);
          reject(error);
        });
        
      } catch (error) {
        console.error('PDF setup error:', error);
        reject(error);
      }
    });
  }

  private generateCoverPage(doc: any, analysisResult: any) {
    // Header
    doc.fontSize(14)
       .fillColor('#64748B')
       .text('HUEMATCHER PROFESSIONAL COLOR ANALYSIS', 50, 80, { align: 'center' });
    
    // Main title
    doc.fontSize(36)
       .fillColor('#1E293B')
       .font('Helvetica-Bold')
       .text(analysisResult.season, 50, 150, { align: 'center' });
    
    // Tagline
    doc.fontSize(16)
       .fillColor('#475569')
       .font('Helvetica')
       .text('Bold, Dramatic, Sophisticated', 50, 200, { align: 'center' });
    
    // Description box
    doc.rect(70, 280, 450, 120)
       .fillColor('#F1F5F9')
       .fill();
    
    doc.rect(70, 280, 450, 120)
       .strokeColor('#CBD5E1')
       .lineWidth(1)
       .stroke();
    
    doc.fontSize(12)
       .fillColor('#334155')
       .font('Helvetica')
       .text(analysisResult.description, 90, 300, { 
         width: 410, 
         align: 'center',
         lineGap: 4
       });
    
    // Signature quote
    doc.fontSize(14)
       .fillColor('#7C3AED')
       .font('Helvetica-Oblique')
       .text('"High contrast combinations with cool undertones create your most powerful looks."', 70, 450, { 
         width: 450, 
         align: 'center' 
       });
    
    // Footer
    doc.fontSize(10)
       .fillColor('#94A3B8')
       .font('Helvetica')
       .text(`Generated by HueMatcher AI • ${new Date().toLocaleDateString()}`, 50, 720, { align: 'center' });
  }

  private generatePalettePage(doc: any, analysisResult: any) {
    // Title
    doc.fontSize(28)
       .fillColor('#1E293B')
       .font('Helvetica-Bold')
       .text('Your Complete Color Palette', 50, 80, { align: 'center' });

    doc.fontSize(12)
       .fillColor('#64748B')
       .font('Helvetica')
       .text('Professional color collection calibrated for your unique features', 50, 120, { align: 'center' });

    let yPos = 170;
    
    // Foundation Neutrals
    this.drawColorSection(doc, 'Foundation Neutrals', 
      'Your essential building blocks - mix and match with confidence',
      analysisResult.coreNeutrals, yPos);
    
    yPos += 150;
    
    // Accent Lights
    this.drawColorSection(doc, 'Accent Lights',
      'Soft highlights that enhance your natural glow',
      analysisResult.accentLights, yPos);
    
    yPos += 150;
    
    // Statement Brights
    this.drawColorSection(doc, 'Statement Brights',
      'Your power colors - use sparingly for maximum impact',
      analysisResult.accentBrights, yPos);
  }

  private generateRecommendationsPage(doc: any, analysisResult: any) {
    // Title
    doc.fontSize(28)
       .fillColor('#1E293B')
       .font('Helvetica-Bold')
       .text('Professional Styling Guide', 50, 80, { align: 'center' });
    
    let yPos = 150;
    
    // Metals
    this.drawRecommendationBox(doc, 'Best Metals & Jewelry', 
      analysisResult.recommendations.metals, yPos);
    yPos += 120;
    
    // Makeup
    this.drawRecommendationBox(doc, 'Makeup & Beauty', 
      analysisResult.recommendations.makeup, yPos);
    yPos += 120;
    
    // Eyewear
    this.drawRecommendationBox(doc, 'Eyewear & Frames', 
      analysisResult.recommendations.eyewear, yPos);
    yPos += 120;
    
    // Shopping tips
    doc.fontSize(16)
       .fillColor('#374151')
       .font('Helvetica-Bold')
       .text('Shopping Strategy', 70, yPos);
    
    yPos += 30;
    const tips = [
      'Always test colors near your face in natural light',
      'Build outfits around your foundation neutrals',
      'Use bright colors as accent pieces only',
      'Reference your digital color card when shopping'
    ];
    
    tips.forEach(tip => {
      doc.fontSize(11)
         .fillColor('#4B5563')
         .font('Helvetica')
         .text('• ' + tip, 90, yPos, { width: 430 });
      yPos += 25;
    });
  }

  private drawColorSection(doc: any, title: string, description: string, colors: string[], yPos: number) {
    // Section title
    doc.fontSize(16)
       .fillColor('#374151')
       .font('Helvetica-Bold')
       .text(title, 70, yPos);
    
    // Description
    doc.fontSize(10)
       .fillColor('#6B7280')
       .font('Helvetica')
       .text(description, 70, yPos + 20);
    
    // Color swatches
    const swatchSize = 35;
    const swatchSpacing = 50;
    const startX = 70;
    
    colors.forEach((color, index) => {
      const x = startX + (index * swatchSpacing);
      const y = yPos + 45;
      
      // Color swatch
      doc.rect(x, y, swatchSize, swatchSize)
         .fillColor(color)
         .fill();
      
      // Border
      doc.rect(x, y, swatchSize, swatchSize)
         .strokeColor('#E5E7EB')
         .lineWidth(1)
         .stroke();
      
      // Color code
      doc.fontSize(7)
         .fillColor('#374151')
         .text(color, x - 5, y + swatchSize + 5, { 
           width: swatchSize + 10, 
           align: 'center' 
         });
    });
  }

  private drawRecommendationBox(doc: any, title: string, content: string, yPos: number) {
    // Box background
    doc.rect(70, yPos, 450, 80)
       .fillColor('#F9FAFB')
       .fill();
    
    // Box border
    doc.rect(70, yPos, 450, 80)
       .strokeColor('#E5E7EB')
       .lineWidth(1)
       .stroke();
    
    // Title
    doc.fontSize(14)
       .fillColor('#374151')
       .font('Helvetica-Bold')
       .text(title, 90, yPos + 15);
    
    // Content
    doc.fontSize(11)
       .fillColor('#4B5563')
       .font('Helvetica')
       .text(content, 90, yPos + 35, { width: 410, lineGap: 3 });
  }
}

export const workingPdfService = new WorkingPDFService();