export function TermsOfService() {
  return (
    <div className="mx-auto max-w-3xl px-6 pb-24 pt-32 lg:px-12">
      <h1 className="font-display text-display-lg font-bold text-charcoal">Terms of Service</h1>
      <p className="mt-4 text-sm text-charcoal/40">Last updated: March 10, 2026</p>

      <div className="mt-10 space-y-8 text-charcoal/60 [&_h2]:mt-10 [&_h2]:font-display [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:text-charcoal [&_p]:mt-3 [&_p]:leading-relaxed [&_ul]:mt-3 [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:leading-relaxed">
        <section>
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using the Hazel & Hue application and website (the "Service"), you agree to be bound by these
            Terms of Service ("Terms"). If you do not agree to these Terms, please do not use the Service.
          </p>
        </section>

        <section>
          <h2>2. Description of Service</h2>
          <p>
            Hazel & Hue provides AI-powered seasonal color analysis. Users upload a selfie photo, and our AI generates a
            personalized color palette, style guide, makeup recommendations, and hair color suggestions based on their
            unique coloring. The Service is available via our mobile application (iOS and Android) and website.
          </p>
        </section>

        <section>
          <h2>3. Eligibility</h2>
          <p>
            You must be at least 13 years old to use the Service. By using the Service, you represent and warrant that you
            meet this age requirement. If you are under 18, you must have parental or guardian consent to use the Service.
          </p>
        </section>

        <section>
          <h2>4. User Accounts</h2>
          <p>
            You may be required to create an account to access certain features. You are responsible for maintaining the
            confidentiality of your account credentials and for all activities that occur under your account. You agree to
            notify us immediately of any unauthorized use of your account.
          </p>
        </section>

        <section>
          <h2>5. User Content</h2>
          <p>
            By uploading photos or other content to the Service, you grant Hazel & Hue a limited, non-exclusive license to
            process that content solely for the purpose of providing the color analysis Service to you. You retain all
            ownership rights to your content.
          </p>
          <p>You agree not to upload content that:</p>
          <ul>
            <li>Violates any applicable law or regulation.</li>
            <li>Infringes on any third party's intellectual property or privacy rights.</li>
            <li>Contains malicious software or harmful code.</li>
            <li>Is obscene, offensive, or otherwise objectionable.</li>
          </ul>
        </section>

        <section>
          <h2>6. Referral Program</h2>
          <p>
            Our referral program allows you to unlock your color analysis results by sharing the Service with friends. The
            terms of the referral program may change at any time. Abuse of the referral system, including creating fake
            accounts or using fraudulent referral methods, may result in account suspension or termination.
          </p>
        </section>

        <section>
          <h2>7. Intellectual Property</h2>
          <p>
            The Service, including its design, text, graphics, logos, icons, images, AI models, and software, is the
            property of Hazel & Hue and is protected by copyright, trademark, and other intellectual property laws. You
            may not reproduce, distribute, modify, or create derivative works from any part of the Service without our
            prior written consent.
          </p>
        </section>

        <section>
          <h2>8. Disclaimer of Warranties</h2>
          <p>
            The Service is provided "as is" and "as available" without warranties of any kind, whether express or implied.
            Color analysis results are generated by AI and are intended as recommendations only. We do not guarantee the
            accuracy, completeness, or suitability of any analysis results. Individual results may vary.
          </p>
        </section>

        <section>
          <h2>9. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, Hazel & Hue shall not be liable for any indirect, incidental, special,
            consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly,
            or any loss of data, use, goodwill, or other intangible losses resulting from your use of the Service.
          </p>
        </section>

        <section>
          <h2>10. Termination</h2>
          <p>
            We may suspend or terminate your access to the Service at any time, with or without cause, and with or without
            notice. Upon termination, your right to use the Service will immediately cease. All provisions of these Terms
            that by their nature should survive termination shall survive.
          </p>
        </section>

        <section>
          <h2>11. Changes to Terms</h2>
          <p>
            We reserve the right to modify these Terms at any time. We will provide notice of material changes by updating
            the "Last updated" date. Your continued use of the Service after changes are posted constitutes your acceptance
            of the revised Terms.
          </p>
        </section>

        <section>
          <h2>12. Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, United
            States, without regard to its conflict of law provisions.
          </p>
        </section>

        <section>
          <h2>13. Affiliate Links & Shopping</h2>
          <p>
            The Service may include links to third-party retailer websites ("Affiliate Links"). When you click
            on an Affiliate Link and make a purchase, Hazel & Hue may earn a small commission at no additional
            cost to you. This commission helps support the continued development and operation of the Service.
          </p>
          <p>
            Affiliate relationships do not influence our color analysis results or product recommendations.
            Our color-matching algorithm scores products purely based on perceptual color distance from your
            personal palette. We do not accept payment from retailers to influence product rankings or recommendations.
          </p>
          <p>
            Product availability, pricing, and shipping are determined entirely by the third-party retailers.
            Hazel & Hue is not responsible for the quality, availability, or delivery of products purchased
            through Affiliate Links. Any issues with purchases should be directed to the relevant retailer.
          </p>
        </section>

        <section>
          <h2>14. Contact Us</h2>
          <p>
            If you have any questions about these Terms, please contact us at{' '}
            <a href="mailto:support@hazelandhue.com" className="text-hazel underline">support@hazelandhue.com</a>.
          </p>
        </section>
      </div>
    </div>
  );
}
